// eli15/chapters/lineage.js
// parentIds and family trees — how we reconstruct who begat who.
export default {
  id: 'lineage',
  title: 'Every brain has parents',
  oneLiner: 'parentIds + getLineage() reconstruct a brain\'s family tree on demand.',
  body: [
    '<p>When a generation ends, the best car\'s brain gets archived — but we don\'t just',
    'save the 244 weights. We also save <strong>which brains it came from</strong>. Each',
    'archive entry carries a <code>parentIds: string[]</code>: the ids of the seeds the GA',
    'warm-started this batch from. Those parents have their <em>own</em> parents stored',
    'alongside their weights. String enough of those together and you have a <strong>family',
    'tree</strong> of neural networks.</p>',
    '<p><code>ruvectorBridge.js:1338</code> exposes <code>getLineage(id, maxDepth = 6)</code>.',
    'Starting from any brain id, it walks <code>parentIds</code> backwards. When a brain has',
    'multiple parents (the batch was seeded from multiple retrievals), it picks the parent',
    'with the highest fitness — <em>"the line of descent we credit this genome to"</em>. The',
    'walk is cycle-safe (a <code>Set</code> of visited ids prevents infinite loops) and',
    'depth-capped so a pathological graph can\'t blow the stack. It returns entries',
    'oldest → newest, ancestor first, queried id last.</p>',
    '<p>Why track this? Two reasons. First, debugging: when a brain suddenly performs way',
    'better on a new track, you can trace <em>which ancestor brain on which old track</em>',
    'planted the useful weights. Second, future work: the GNN reranker (planned, replacing',
    'the EMA) will use the lineage DAG as its <em>graph</em> — neighbour nodes in the graph',
    'are literally the parent and child brains.</p>',
    '<p>In the UI, each retrieved seed in the Vector Memory panel shows a tiny sparkline of',
    'its lineage\'s fitness trajectory: the leftmost dot is the oldest ancestor, the',
    'rightmost (with a darker marker) is the seed itself. A rising line means this seed',
    'is the product of successive improvements; a flat line means no one in the family',
    'ever got much better.</p>',
    '<h3>Try it yourself</h3>',
    '<ul><li>Open DevTools during phase 4 and run',
    '<code>window.__rvBridge.getLineage(window.currentSeedIds[0])</code>. You\'ll see an',
    'array like <code>[{id, fitness, generation}, ...]</code> — the family tree of the top',
    'seed that just warm-started this generation.</li></ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '            ancestor             current seed',
    '   gen 3      ●─────┐                ',
    '                    ▼                ',
    '   gen 5           ●────────┐        ',
    '                            ▼        ',
    '   gen 9                   ●──────┐  ',
    '                                  ▼  ',
    '   gen 14                        ●  ← getLineage(id) returns this trail',
    '',
    '  sparkline in the seed row:',
    '     ─── ─── ─── ─●          (fitness oldest→newest)',
    '</pre>',
  ].join('\n'),
  related: [
    'genetic-algorithm',
    'ema-reranker',
    'vectordb-hnsw',
  ],
};
