// eli15/chapters/neural-network.js
// The 244-weight 10→16→4 feed-forward network that decides W/A/S/D.
export default {
  id: 'neural-network',
  title: 'A brain made of 244 numbers',
  oneLiner: 'Ten sensor inputs → sixteen hidden neurons → four pedal/steer outputs.',
  body: [
    '<p>Every car carries a tiny neural network. It is almost comically small:',
    '<strong>10 inputs → 16 hidden neurons → 4 outputs</strong>. See it in',
    '<code>network.js</code> (the <code>Level</code> and <code>NeuralNetwork</code> classes) and',
    '<code>car.js:41-42</code> where the car wires it up.</p>',
    '<p>"A neuron" here is just a weighted sum with a threshold. It multiplies each input',
    'by a <strong>weight</strong>, adds them all up, and compares the total to a <strong>bias</strong>.',
    'If the sum beats the bias, the neuron fires a 1. Otherwise a 0. That\'s it — no fancy',
    'activation function, no backprop, no gradients. The whole network can be serialised',
    'as a flat <code>Float32Array(244)</code> — see <code>brainCodec.js:5</code>:',
    '<code>FLAT_LENGTH = 244</code>. Where does 244 come from? For each layer with <em>in</em>',
    'inputs and <em>out</em> outputs you need <em>in × out</em> weights plus <em>out</em> biases:',
    '<code>(10×16 + 16) + (16×4 + 4) = 176 + 68 = 244</code>.</p>',
    '<p>The four outputs are Boolean: <em>forward</em>, <em>reverse</em>, <em>left</em>, <em>right</em>.',
    'The car presses the pedals whose neuron fired a 1. Combine that with the 7 rays + 3 features',
    ' from <code>sensors</code> + car and you get the whole perception-to-action pipeline',
    'in ~50 lines of JS.</p>',
    '<p>No learning happens inside the brain itself — the brain is just a lookup function.',
    'Learning happens <em>across generations</em>, by the genetic algorithm tweaking those 244',
    'numbers.</p>',
    '<h3>Try it yourself</h3>',
    '<ul><li>In phase 4, watch the four-box display in the right panel (the',
    '<code>inputCanvas</code>). Each box turns blue when the corresponding output neuron',
    'fires. That\'s the neural net\'s decision for the best car, frame by frame.</li></ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '  INPUTS (10)     HIDDEN (16)        OUTPUTS (4)',
    '',
    '   ray 0  ●───┐',
    '   ray 1  ●───┼─── ●─┐',
    '   ray 2  ●───┼─── ●─┼──── ● forward',
    '   ray 3  ●───┼─── ●─┼──── ● reverse',
    '   ray 4  ●───┼─── ●─┼──── ● left',
    '   bias   ●───┘    ●─┼──── ● right',
    '                   ●─┘',
    '                   ●',
    '                   ●',
    '',
    '   weights + biases:',
    '     layer 0 → 1 :  10×16 + 16  =  176',
    '     layer 1 → 2 :  16×4 + 4  =  68',
    '                        total = 244 floats',
    '</pre>',
  ].join('\n'),
  related: [
    'sensors',
    'genetic-algorithm',
    'cnn-embedder',
  ],
};
