// eli15/chapters/sensors.js
// Ray-cast sensors: how a 2D neural-net car "sees" without having eyes.
export default {
  id: 'sensors',
  title: 'The car\'s eyes are seven invisible rays',
  oneLiner: 'Ray-cast sensors feed a number per ray into the neural network.',
  body: [
    '<p>Real cars have cameras, LIDAR, radar. Our cars can\'t afford any of that —',
    'they live in a 2D canvas. So instead of pixels, each car shoots out <strong>7 straight',
    'rays</strong> from its nose (<code>sensor.js</code>: <code>rayCount = 7</code>, spread over 120°).',
    'Every frame, each ray asks a simple question: <em>"how close is the nearest road',
    'border in this direction?"</em></p>',
    '<p>The answer is a single number between 0 and 1. 0 means "wall is right on top of me".',
    '1 means "nothing in sight for 400 pixels" (<code>rayLength = 400</code>). The ray doesn\'t',
    'care <em>what</em> it hit — just <em>how far away</em> it was. This is what\'s called a',
    '<strong>distance sensor</strong>, and it\'s the cheapest possible way to give a brain',
    'something useful to think about.</p>',
    '<p>Why 7? It used to be 5, but 5 rays in a 120° fan leave 30° gaps between adjacent',
    'rays — wide enough to hide an apex corner until the car is already on top of it.',
    'Bumping to 7 closes those gaps to ~17°. Combined with speed and two track-orientation',
    'features, that\'s the <strong>10 inputs</strong> feeding the first hidden layer.',
    'Look at <code>car.js:42</code> and you\'ll see it: <code>new NeuralNetwork([sensor.rayCount+3, 16, 4])</code>.</p>',
    '<p>The rays are drawn on the training canvas as faint lines sticking out of each car.',
    'Where a ray hits a wall, there\'s a tiny dot. That dot\'s distance is what the brain sees.</p>',
    '<h3>Try it yourself</h3>',
    '<ul><li>During phase 4 (training), zoom the browser in and watch the faint yellow rays',
    'poke out of a car\'s nose. When the car hugs a wall, the nearest ray reading drops',
    'toward 0 — and the brain reacts by steering away.</li></ul>',
  ].join('\n'),
  diagram: [
    '<pre class="eli15-ascii">',
    '         ray 0        ray 2 (straight)',
    '           \\           |           /',
    '            \\          |          /  ray 4',
    '             \\   ray 1 | ray 3  /',
    '              \\    \\   |   /   /',
    '               \\    \\  |  /   /',
    '                \\    \\ | /   /',
    '                 \\    \\|/   /',
    '                  [ C A R ]',
    '',
    '  each ray returns a single number in [0, 1]:',
    '     0 = wall touching nose',
    '     1 = clear for 400px',
    '',
    '  7 rays + 3 features → feeds NN layer 0 (10 neurons)',
    '</pre>',
  ].join('\n'),
  related: [
    'neural-network',
    'genetic-algorithm',
    'what-is-this-project',
  ],
};
