// Rebuild the committed, same-origin runtime. Serving the app needs no npm step.
import { build } from 'esbuild';
import { mkdir, copyFile, writeFile } from 'node:fs/promises';
import { createRequire } from 'node:module';
const require = createRequire(import.meta.url);
const output = 'vendor/three-0.186.0';
await mkdir(output, { recursive: true });
await build({
  stdin: { contents: `
    export * from 'three/webgpu';
    export { OrbitControls } from 'three/addons/controls/OrbitControls.js';
    export { RoundedBoxGeometry } from 'three/addons/geometries/RoundedBoxGeometry.js';
    export { mergeGeometries } from 'three/addons/utils/BufferGeometryUtils.js';
    export { bloom } from 'three/addons/tsl/display/BloomNode.js';
    export { pass, mrt, output, emissive, texture, positionWorld, positionLocal,
      uniform, float, vec2, vec3, mix, time, fract, attribute, mx_noise_float,
      reflector } from 'three/tsl';
  `, resolveDir: process.cwd() },
  plugins: [{ name: 'same-three-build', setup(b) {
    b.onResolve({ filter: /^three$/ }, () => ({ path: require.resolve('three/webgpu') }));
  } }],
  bundle: true, format: 'esm', target: 'es2022', minify: true,
  legalComments: 'eof', outfile: `${output}/three.js`,
});
await copyFile('node_modules/three/LICENSE', `${output}/LICENSE`);
await writeFile(`${output}/README.md`, '# Three.js r186\n\nMIT licensed Three.js 0.186.0 and its addons. Generated by `npm run vendor:three`.\nAll imports use the same WebGPU build; there are no runtime CDN requests.\n');
